# Generated by Django 6.0.3 on 2026-03-09 05:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Designation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('salary_type', models.CharField(choices=[('DAILY', 'Daily'), ('MONTHLY', 'Monthly')], max_length=10)),
                ('base_salary', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Shift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('standard_hours', models.DecimalField(decimal_places=1, default=8.0, max_digits=4)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.CharField(blank=True, max_length=10, unique=True)),
                ('name', models.CharField(max_length=150)),
                ('date_of_joining', models.DateField()),
                ('contact_number', models.CharField(max_length=15)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='employee_photos/')),
                ('designation', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='hr.designation')),
            ],
        ),
    ]
