# Generated by Django 6.0.3 on 2026-03-09 05:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='aadhaar_pdf',
            field=models.FileField(blank=True, null=True, upload_to='employee_docs/aadhaar/'),
        ),
        migrations.AddField(
            model_name='employee',
            name='blood_group',
            field=models.CharField(blank=True, max_length=5),
        ),
        migrations.AddField(
            model_name='employee',
            name='has_esi_pf',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='designation',
            name='base_salary',
            field=models.DecimalField(decimal_places=2, help_text='Daily rate for workers, Monthly for staff', max_digits=10),
        ),
        migrations.AlterField(
            model_name='employee',
            name='designation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='employees', to='hr.designation'),
        ),
        migrations.CreateModel(
            name='AdvancePayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date_given', models.DateField()),
                ('is_deducted', models.BooleanField(default=False)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='advances', to='hr.employee')),
            ],
        ),
        migrations.CreateModel(
            name='DailySalaryEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('shift_value', models.DecimalField(decimal_places=2, default=1.0, help_text='1.0=Full, 0.5=Half', max_digits=3)),
                ('worked_hours', models.DecimalField(decimal_places=1, default=8.0, max_digits=4)),
                ('ot_hours', models.DecimalField(decimal_places=1, default=0.0, max_digits=4)),
                ('amount_earned', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=8)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_entries', to='hr.employee')),
            ],
            options={
                'unique_together': {('employee', 'date')},
            },
        ),
        migrations.CreateModel(
            name='MonthlySalarySummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month_year', models.DateField(help_text='Select the 1st day of the month')),
                ('total_days_present', models.IntegerField(default=0)),
                ('total_shifts_worked', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('total_hours_worked', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
                ('gross_salary', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('advance_deducted', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('net_payable', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('status', models.CharField(choices=[('UNPAID', 'Unpaid'), ('PAID', 'Paid')], default='UNPAID', max_length=10)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monthly_summaries', to='hr.employee')),
            ],
            options={
                'unique_together': {('employee', 'month_year')},
            },
        ),
    ]
