# Generated by Django 6.0.3 on 2026-03-09 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0002_employee_aadhaar_pdf_employee_blood_group_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='designation',
            name='standard_shift_hours',
            field=models.DecimalField(decimal_places=1, default=8.0, max_digits=4),
        ),
        migrations.AlterField(
            model_name='dailysalaryentry',
            name='amount_earned',
            field=models.DecimalField(decimal_places=2, editable=False, max_digits=8),
        ),
        migrations.AlterField(
            model_name='dailysalaryentry',
            name='shift_value',
            field=models.DecimalField(decimal_places=2, default=1.0, help_text='1.0, 0.5, 1.5, etc.', max_digits=3),
        ),
        migrations.AlterField(
            model_name='dailysalaryentry',
            name='worked_hours',
            field=models.DecimalField(decimal_places=1, default=0, editable=False, max_digits=4),
        ),
        migrations.AlterField(
            model_name='designation',
            name='base_salary',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='shift',
            name='name',
            field=models.CharField(help_text='e.g., Shift A, Night, General', max_length=50, unique=True),
        ),
    ]
