# Generated by Django 6.0.3 on 2026-03-09 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0003_designation_standard_shift_hours_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shift',
            options={'ordering': ['shift_value']},
        ),
        migrations.RemoveField(
            model_name='shift',
            name='name',
        ),
        migrations.AddField(
            model_name='shift',
            name='shift_value',
            field=models.DecimalField(decimal_places=2, default=1.0, help_text='0.5 = 4 hrs, 1.0 = 8 hrs (1 shift). Hours = shift_value × standard_hours.', max_digits=3, unique=True),
        ),
        migrations.AlterField(
            model_name='shift',
            name='standard_hours',
            field=models.DecimalField(decimal_places=1, default=8.0, help_text='Hours for shift_value=1.0 (e.g. 8).', max_digits=4),
        ),
    ]
