# Generated by Django 6.0.3 on 2026-03-09 08:53

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0004_alter_shift_options_remove_shift_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailysalaryentry',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dailysalaryentry',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Uncheck this if the employee leaves or the record is disabled.'),
        ),
        migrations.AddField(
            model_name='dailysalaryentry',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='designation',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='designation',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Uncheck this if the employee leaves or the record is disabled.'),
        ),
        migrations.AddField(
            model_name='designation',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employee',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Uncheck this if the employee leaves or the record is disabled.'),
        ),
        migrations.AddField(
            model_name='employee',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='shift',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shift',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Uncheck this if the employee leaves or the record is disabled.'),
        ),
        migrations.AddField(
            model_name='shift',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='shift',
            name='shift_value',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=3, unique=True),
        ),
        migrations.AlterField(
            model_name='shift',
            name='standard_hours',
            field=models.DecimalField(decimal_places=1, default=8.0, max_digits=4),
        ),
    ]
