# Generated by Django 6.0.3 on 2026-03-09 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0005_dailysalaryentry_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shift',
            name='shift_value',
            field=models.DecimalField(decimal_places=1, default=1.0, max_digits=3, unique=True),
        ),
        migrations.AlterField(
            model_name='shift',
            name='standard_hours',
            field=models.PositiveIntegerField(default=8),
        ),
    ]
