# Generated by Django 6.0.3 on 2026-03-09 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0006_alter_shift_shift_value_alter_shift_standard_hours'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='designation',
            name='standard_shift_hours',
        ),
    ]
