# Generated by Django 6.0.3 on 2026-03-09 10:49

import hr.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0007_remove_designation_standard_shift_hours'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='name',
            new_name='employee_name',
        ),
        migrations.AddField(
            model_name='employee',
            name='address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='appointment_order',
            field=models.FileField(blank=True, null=True, upload_to='employee_docs/appointment_orders/', validators=[hr.utils.validate_pdf_size]),
        ),
        migrations.AddField(
            model_name='employee',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='district',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='employee',
            name='education_qualification',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='employee',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='experience',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='pan_pdf',
            field=models.FileField(blank=True, null=True, upload_to='employee_docs/pan/', validators=[hr.utils.validate_pdf_size]),
        ),
        migrations.AddField(
            model_name='employee',
            name='passbook_pdf',
            field=models.FileField(blank=True, null=True, upload_to='employee_docs/passbook/', validators=[hr.utils.validate_pdf_size]),
        ),
        migrations.AlterField(
            model_name='employee',
            name='aadhaar_pdf',
            field=models.FileField(blank=True, null=True, upload_to='employee_docs/aadhaar/', validators=[hr.utils.validate_pdf_size]),
        ),
        migrations.AlterField(
            model_name='employee',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='employee_photos/', validators=[hr.utils.validate_photo_size]),
        ),
    ]
