# Generated by Django 6.0.3 on 2026-03-09 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0008_rename_name_employee_employee_name_employee_address_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='designation',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('name',), name='unique_active_designation_name'),
        ),
        migrations.AddConstraint(
            model_name='employee',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('employee_id',), name='unique_active_employee_id'),
        ),
        migrations.AddConstraint(
            model_name='shift',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('shift_value',), name='unique_active_shift_value'),
        ),
    ]
