# Generated by Django 6.0.3 on 2026-03-09 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0009_designation_unique_active_designation_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='designation',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='shift',
            name='shift_value',
            field=models.DecimalField(decimal_places=1, default=1.0, max_digits=3),
        ),
    ]
