# Generated by Django 4.2.28 on 2026-03-10 04:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0010_alter_designation_name_alter_shift_shift_value'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='advancepayment',
            name='is_deducted',
        ),
        migrations.AddField(
            model_name='advancepayment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='advancepayment',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Uncheck this if the employee leaves or the record is disabled.'),
        ),
        migrations.AddField(
            model_name='advancepayment',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
