# Generated by Django 4.2.28 on 2026-03-10 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0011_remove_advancepayment_is_deducted_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailysalaryentry',
            name='amount_earned',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=8),
        ),
    ]
