# Generated by Django 4.2.28 on 2026-03-10 05:30

from django.db import migrations, models
import django.utils.timezone
import datetime

class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0012_alter_dailysalaryentry_amount_earned'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='monthlysalarysummary',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='dailysalaryentry',
            name='day',
            field=models.PositiveIntegerField(default=1, help_text='Day (default 1)'),
        ),
        migrations.AddField(
            model_name='monthlysalarysummary',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
    model_name='monthlysalarysummary',
    name='date',
    field=models.DateField(default=datetime.date(2000, 1, 1)),
    preserve_default=False,
),
        migrations.AddField(
            model_name='monthlysalarysummary',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Uncheck this if the employee leaves or the record is disabled.'),
        ),
        migrations.AddField(
            model_name='monthlysalarysummary',
            name='total_days',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=3),
        ),
        migrations.AddField(
            model_name='monthlysalarysummary',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterUniqueTogether(
            name='monthlysalarysummary',
            unique_together={('employee', 'date')},
        ),
        migrations.RemoveField(
            model_name='monthlysalarysummary',
            name='month_year',
        ),
        migrations.RemoveField(
            model_name='monthlysalarysummary',
            name='total_days_present',
        ),
    ]
