# Generated by Django 4.2.28 on 2026-03-10 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0013_add_day_to_dailysalaryentry'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailysalaryentry',
            name='total_hours',
            field=models.DecimalField(decimal_places=1, default=0, editable=False, max_digits=4),
        ),
    ]
