# Generated by Django 4.2.28 on 2026-03-10 10:33

from django.db import migrations, models
import hr.utils


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0014_add_total_hours_to_dailysalaryentry'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, help_text='Uncheck this if the employee leaves or the record is disabled.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('day', models.PositiveIntegerField()),
                ('file', models.FileField(upload_to='certificates/', validators=[hr.utils.validate_pdf_size, hr.utils.validate_pdf_size])),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterModelOptions(
            name='monthlysalarysummary',
            options={'ordering': ['-date', 'employee_id']},
        ),
    ]
