# Generated by Django 4.2.28 on 2026-03-11 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0016_employee_account_number_employee_bank_branch_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='aadhaar_number',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='employee',
            name='about',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='country',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='employee',
            name='esi_account_number',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='employee',
            name='pan_number',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='employee',
            name='pf_account_number',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
