# Generated by Django 4.2.28 on 2026-03-11 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0017_employee_aadhaar_number_employee_about_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='esi_amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='pf_amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='monthlysalarysummary',
            name='esi_deduction',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='monthlysalarysummary',
            name='pf_deduction',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True),
        ),
    ]
