# Generated by Django 4.2.28 on 2026-03-11 09:10

from django.db import migrations, models
import hr.utils
import datetime

class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0018_employee_esi_amount_employee_pf_amount_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='monthlysalarysummary',
            old_name='esi_deduction',
            new_name='esi_amount',
        ),
        migrations.RenameField(
            model_name='monthlysalarysummary',
            old_name='pf_deduction',
            new_name='pf_amount',
        ),
        migrations.RemoveField(
            model_name='certificate',
            name='day',
        ),
     migrations.AddField(
    model_name='certificate',
    name='date',
    field=models.DateField(default=datetime.date.today),
    preserve_default=False,
),
        migrations.AlterField(
            model_name='certificate',
            name='file',
            field=models.ImageField(upload_to='certificates/', validators=[hr.utils.validate_photo_size_certificate]),
        ),
    ]
