# Generated by Django 4.2.28 on 2026-03-12 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0019_rename_esi_deduction_monthlysalarysummary_esi_amount_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='monthlysalarysummary',
            name='status',
        ),
        migrations.AddField(
            model_name='monthlysalarysummary',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
    ]
