# Generated by Django 4.2.28 on 2026-03-13 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0020_remove_monthlysalarysummary_status_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='monthlysalarysummary',
            constraint=models.CheckConstraint(check=models.Q(('net_payable__gte', 0)), name='net_payable_non_negative'),
        ),
    ]
