# Generated by Django 4.2.28 on 2026-03-16 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0021_monthlysalarysummary_net_payable_non_negative'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='advancepayment',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('employee', 'date_given'), name='unique_active_advance_per_employee_per_day'),
        ),
    ]
