# Generated by Django 4.2.28 on 2026-03-18 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0022_advancepayment_unique_active_advance_per_employee_per_day'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='dailysalaryentry',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='dailysalaryentry',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('employee', 'date'), name='unique_active_daily_entry_per_employee_per_day'),
        ),
    ]
